spring:
  profiles:
    active: dev
  application:
    name: sales-api
  datasource:
    hikari:
      data-source-properties:
        reWriteBatchedInserts: true
        prepareThreshold: 5
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    generate-ddl: true
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        generate_statistics: true
        order_updates: true
        order_inserts: true
        show_sql: true
        jdbc:
          batch_size: 50
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true
  rabbitmq:
    listener:
      simple:
        prefetch: 100


rabbitmq:
  sales-api:
    queue-name:
        create-event: "event-ticketing-platform.sales-api.queue.create-event"
    routing-key:
        create-event: "event-ticketing-platform.sales-api.routing-key.create-event"

  exchange-name:
      exchange: "event-ticketing-platform.sales-api.exchange.create-event"
