spring:
  application:
    name: sales-api
  datasource:
    hikari:
      data-source-properties:
        reWriteBatchedInserts: true
        prepareThreshold: 5
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    open-in-view: false
    properties:
      hibernate:
        order_updates: true
        order_inserts: true
        jdbc:
          batch_size: ${database.batch-size}
  threads:
    virtual:
      enabled: true
  mvc:
    problemdetails:
      enabled: true
  rabbitmq:
    listener:
      simple:
        prefetch: 100
        default-requeue-rejected: false
        acknowledge-mode: auto
    publisher-confirm-type: correlated
    template:
      mandatory: true
    publisher-returns: true
  flyway:
    locations: classpath:db/migration
    enabled: true

database:
  batch-size: 50

messaging-scheduler:
  batches-processing-at-once: 3

rabbitmq:
  consumer:
    max-retries: 3
    max-delay: 12
    multiplier: 2.0
    delay: 3
  sales-api:
    create-event:
      queue-name: "event-ticketing-platform.sales-api.create-event.queue"
      routing-key: "event-ticketing-platform.sales-api.create-event.routing-key"
      dlq: "event-ticketing-platform.sales-api.create-event.dlq"
      dlq-routing-key: "event-ticketing-platform.sales-api.create-event.dlq-routing-key"
      consumer-name: "seat-service"
  exchange:
    main-exchange: "event-ticketing-platform.main-exchange"
    dead-letter-exchange: "event-ticketing-platform.dead-letter-exchange"
stripe:
  idempotency-key:
    prefix: "payment-intent:order:"
order:
  time-to-expired: 15
