spring:
  config:
    import: file:./local.secrets.properties
  datasource:
    url: jdbc:postgresql://localhost:5432/event-ticketing-platform-db
    username: admin
    password: admin

  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true

  rabbitmq:
    username: admin
    password: admin
    port: 5672
    host: localhost

jwt-secret-key: ${local.secret.jwt-secret-key}

stripe:
  secret-key: ${local.secret.stripe.secret-key}
