spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event-ticketing-platform-db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
  rabbitmq:
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    port: ${RABBITMQ_NODE_PORT}
    host: localhost
