services:
  event-ticketing-platform-db:
    image: postgres:17.10
    container_name: "event-ticketing-platform-db"
    environment:
      - "POSTGRES_DB"
      - "POSTGRES_USER"
      - "POSTGRES_PASSWORD"
    volumes:
       - event-ticketing-platform-db-volume:/var/lib/postgresql/data
    networks:
      - main-network
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 30s
      timeout: 10s
      retries: 5
  event-ticketing-platform-message-broker:
    image: rabbitmq:4.3.2-management
    container_name: "event-ticketing-platform-message-broker"
    ports:
      - "${RABBITMQ_MANAGEMENT_TCP_PORT}:${RABBITMQ_MANAGEMENT_TCP_PORT}"
      - "${RABBITMQ_NODE_PORT}:${RABBITMQ_NODE_PORT}"
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}"
      - "RABBITMQ_CONFIG_FILE=${RABBITMQ_CONFIG_FILE}"
    volumes:
      - ./rabbitmq:/config/rabbitmq
      - event-ticketing-platform-message-broker-volume:/var/lib/rabbitmq
    networks:
      - main-network


volumes:
  event-ticketing-platform-db-volume:
  event-ticketing-platform-message-broker-volume:
networks:
  main-network: